chat/urls.py
from django.urls import path, include
from chat import views as chat_views
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path("chat/", chat_views.chatPage, name="chat-page"),
    # login-section
    path(
        "auth/login/",
        LoginView.as_view(template_name="chat/LoginPage.html"),
        name="login-user",
    ),
    path("auth/logout/", LogoutView.as_view(), name="logout-user"),
]

lab_projekcik/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from klub_100kilo.views import *
from django.contrib.auth import views as auth_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.views.generic import TemplateView

schema_view = get_schema_view(
    openapi.Info(
        title="Klub 100kilo API",
        default_version="v1",
        description="API for Klub 100kilo",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reservations/", reservation_view, name="reservations"),
    path("", hero_page, name="hero_page"),
    path("main/", main_page, name="main_page"),
    path("signup/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("account/", account, name="account"),
    path(
        "account/change_password/",
        change_password,
        name="change_password",
    ),
    path("account/edit_profile/", edit_profile, name="edit_profile"),
    path(
        "account/password_change_done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="password_change_done.html"
        ),
        name="password_change_done",
    ),
    path("book_trainer/", book_trainer, name="book_trainer"),
    path("measurements/", measurements_view, name="measurements"),
    path(
        "measurements/<int:year>/<int:month>/<int:day>/",
        get_measurements,
        name="get_measurements",
    ),
    path(
        "post_measurements/<int:year>/<int:month>/<int:day>/",
        post_measurements,
        name="post_measurements",
    ),
    path("diets/", diet_view, name="diet"),
    path(
        "diets/<int:year>/<int:month>/<int:day>/", get_diets, name="get_diets"
    ),
    path(
        "post_diets/<int:year>/<int:month>/<int:day>/",
        post_diets,
        name="post_diets",
    ),
    path("book_training/", book_training, name="book_training"),
    path("all_events/", all_events, name="all_events"),
    path("add_event/", add_event, name="add_event"),
    path("update/", update, name="update"),
    path("remove/", remove, name="remove"),
    path("goals/", goals_view, name="goals"),
    path("add_goal/", add_goal, name="add_goal"),
    path("delete_goal/<int:goal_id>/", delete_goal, name='delete_goal'),
    path("workouts/", workouts_view, name="workouts"),
    path("workouts/create_training/", create_training, name="create_training"),
    path("delete_training/<int:training_id>/", delete_training, name='delete_training'),
    path(
        "workouts/mark_exercises_as_succeeded/<int:training_id>/",
        mark_exercises_as_succeeded,
        name="mark_exercises_as_succeeded",
    ),
    path("", include("chat.urls")),
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

klub_100kilo/models.py
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import User
from rest_framework.exceptions import ValidationError


class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    role = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    mail = models.CharField(max_length=100)
    phone_number = models.IntegerField()
    password = models.CharField(max_length=100)

    class Meta:
        db_table = "Users"


class Exercises(models.Model):
    exercise_id = models.AutoField(primary_key=True)
    description = models.CharField(max_length=200)
    muscle_group = models.CharField(max_length=60)
    difficulty = models.CharField(max_length=50)
    category = models.CharField(max_length=50)

    class Meta:
        db_table = "Exercises"


class Gyms(models.Model):
    gym_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)
    phone_number = models.IntegerField()
    address = models.CharField(max_length=80)

    class Meta:
        db_table = "Gyms"


class Measurements(models.Model):
    date = models.DateField(primary_key=True)
    user = models.ForeignKey(
        Users, on_delete=models.DO_NOTHING, db_column="user_ID"
    )
    weight = models.IntegerField(blank=True, null=True)
    biceps_size = models.IntegerField(blank=True, null=True)
    bust_size = models.IntegerField(blank=True, null=True)
    waist_size = models.IntegerField(blank=True, null=True)
    thighs_size = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = "Measurements"


class MeasurementsGoals(models.Model):
    goal_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        Users, on_delete=models.DO_NOTHING, db_column="user_ID"
    )
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    max_days = models.IntegerField()
    weight = models.IntegerField(blank=True, null=True)
    biceps_size = models.IntegerField(blank=True, null=True)
    bust_size = models.IntegerField(blank=True, null=True)
    waist_size = models.IntegerField(blank=True, null=True)
    thighs_size = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=1, default="N")

    class Meta:
        db_table = "Measurements_Goals"


class Reservations(models.Model):
    reservation_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        Users, on_delete=models.CASCADE, db_column="user_ID"
    )
    type = models.CharField(max_length=50)
    status = models.CharField(max_length=1)
    gym = models.ForeignKey(Gyms, on_delete=models.CASCADE, db_column="gym_ID")
    trainer_id = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    start = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True)
    training_id = models.IntegerField(blank=True, null=True)

    def clean(self):
        super().clean()
        if self.start < timezone.now() or self.end < timezone.now():
            raise ValidationError("Start and end times cannot be in the past")

        overlapping_reservations = Reservations.objects.filter(
            user=self.user, start__lt=self.end, end__gt=self.start
        )

        if self.pk:
            overlapping_reservations = overlapping_reservations.exclude(
                pk=self.pk
            )

        if overlapping_reservations.exists():
            raise ValidationError(
                "You have another reservation at the same time"
            )

    class Meta:
        db_table = "Reservations"


class Trainers(models.Model):
    user = models.OneToOneField(
        Users,
        on_delete=models.DO_NOTHING,
        db_column="user_ID",
        primary_key=True,
    )
    hourly_cost = models.DecimalField(max_digits=16, decimal_places=16)
    specialization = models.CharField(max_length=40)
    description = models.CharField(max_length=400)

    class Meta:
        db_table = "Trainers"


class TrainingGoals(models.Model):
    goal_id = models.AutoField(primary_key=True)
    start_date = models.DateField()
    max_days = models.IntegerField()
    muscle_group = models.IntegerField()
    user = models.ForeignKey(
        Users, on_delete=models.DO_NOTHING, db_column="user_ID"
    )

    class Meta:
        db_table = "Training_Goals"


class Trainings(models.Model):
    training_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    user = models.ForeignKey(
        Users, on_delete=models.DO_NOTHING, db_column="user_ID"
    )
    took_place = models.BooleanField(default=False)
    exercises = models.ManyToManyField(Exercises, through="TraningsExercises")

    class Meta:
        db_table = "Trainings"


class TraningsExercises(models.Model):
    training_exercise_id = models.AutoField(primary_key=True)
    training = models.ForeignKey(
        Trainings,
        on_delete=models.DO_NOTHING,
        db_column="training_ID",
    )
    exercise = models.ForeignKey(
        Exercises, on_delete=models.DO_NOTHING, db_column="exercise_ID"
    )
    succeded = models.BooleanField(default=False)

    class Meta:
        db_table = "Tranings_Exercises"
        unique_together = (("training", "exercise"),)


class Diet(models.Model):
    date = models.DateField(primary_key=True)
    user = models.ForeignKey(
        Users, on_delete=models.DO_NOTHING, db_column="user_ID"
    )
    meal = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=600, null=True)
    calories = models.IntegerField(null=True)

    class Meta:
        db_table = "Diet"


class Events(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    start = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "Events"

templates/account.html
{% extends 'base.html' %} {% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Profil użytkownika</h1>
    <div class="box">
      <h2 class="subtitle">Witaj, {{ user.first_name }}!</h2>
      <p>Twoje nazwisko: {{ user.last_name }}</p>
      <p>Twój email: {{ user.email }}</p>
    </div>
    <a class="button is-primary" href="{% url 'edit_profile' %}">Edytuj profil</a>
    <a class="button is-danger" href="{% url 'change_password' %}">Zmień hasło</a>
  </div>
</section>
{% endblock %}

templates/base.html
<!doctype html>
<html style="height: 100%">
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="../static/styles/base.css" />
  </head>
  <body style="display: flex; flex-direction: column; min-height: 100%">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          <i class="fas fa-home"></i>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/reservations"> Rezerwacje </a>
          <a class="navbar-item" href="/diets"> Dieta </a>
          <a class="navbar-item" href="/workouts"> Ułóż trening </a>
          <a class="navbar-item" href="/goals"> Cele </a>
          <a class="navbar-item" href="/measurements"> Pomiary </a>
            <a class="navbar-item" href="/chat"> Czat </a>
        </div>
        <div class="navbar-end">
          <a class="navbar-item" href="/account"> Profil użytkownika </a>
          <div class="navbar-item" href="/logout">
            <form method="POST" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="button is-danger">
                <i class="fas fa-sign-out-alt"></i>
              </button>
            </form>
          </div>
        </div>
      </div>
    </nav>

    <main style="flex: 1">{% block content %} {% endblock %}</main>

    <footer class="footer" style="padding: 1rem 1.5rem">
      <div class="content has-text-centered">
        <p>
          <strong>Autorzy</strong>
          <a href="https://github.com/Davsooonowy">Dawid Mularczyk</a>,
          <a href="https://github.com/HadesXBloodFire">Maciej Wilewski</a>. 2024
        </p>
      </div>
    </footer>
    <script src="../static/scripts/base.js"></script>
  </body>
</html>

templates/book_trainer.html
{% extends "base.html" %} {% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Zarezerwuj trenera</h1>
    <form method="POST" action="{% url 'book_trainer' %}">
      {% csrf_token %}
      <div class="field">
        <label class="label">Wybierz rezerwację</label>
        <div class="control">
          <div class="select">
            <select name="reservation">
              {% for reservation in reservations %}
              <option value="{{ reservation.reservation_id }}">{{ reservation.start }} - {{ reservation.end|date:"H:i" }} </option>
              {% endfor %}
            </select>
          </div>
        </div>
      </div>
      <div class="field">
        <label class="label">Wybierz trenera</label>
        <div class="control">
          <div class="select">
            <select name="trainer">
              {% for trainer in trainers %}
              <option value="{{ trainer.user.user_id }}">
                {{ trainer.user.first_name }} {{ trainer.user.last_name }} {{ trainer.hourly_cost }} zł/h {{ trainer.specialization }}
              </option>
              {% endfor %}
            </select>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <button type="submit" class="button is-link">Zarezerwuj trenera</button>
        </div>
      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/book_training.html
<!doctype html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="../static/styles/base.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/locale/pl.js"></script>
</head>
  <body style="display: flex; flex-direction: column; min-height: 100%">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          <i class="fas fa-home"></i>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/reservations"> Rezerwacje </a>
          <a class="navbar-item" href="/diets"> Dieta </a>
          <a class="navbar-item" href="/workouts"> Ułóż trening </a>
          <a class="navbar-item" href="/golas"> Cele </a>
          <a class="navbar-item" href="/measurements"> Pomiary </a>
        </div>
        <div class="navbar-end">
          <a class="navbar-item" href="/account"> Profil użytkownika </a>
          <div class="navbar-item" href="/logout">
            <form method="POST" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="button is-danger">
                <i class="fas fa-sign-out-alt"></i>
              </button>
            </form>
          </div>
        </div>
      </div>
    </nav>

    <div class="field centered">
      <label class="label">Wybierz siłownię</label>
      <div class="control">
        <div class="select">
          <select id="gym-select">
            {% for gym in gyms %}
            <option value="{{ gym.gym_id }}">{{ gym.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
    </div>

    <main style="flex: 1; padding: 1rem">
        <div class="container">
             <div class="row">
                <div class="col-md-12">
                    <div id='calendar'></div>
                </div>
             </div>
        </div>
    </main>

    <footer class="footer" style="padding: 1rem 1.5rem">
      <div class="content has-text-centered">
        <p>
          <strong>Autorzy</strong>
          <a href="https://github.com/Davsooonowy">Dawid Mularczyk</a>,
          <a href="https://github.com/HadesXBloodFire">Maciej Wilewski</a>. 2024
        </p>
      </div>
    </footer>
    <script src="../static/scripts/book_training.js"></script>
    <script src="../static/scripts/base.js"></script>
  </body>
</html>

templates/change_password.html
{% extends 'base.html' %} {% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Zmień hasło</h1>
    <div class="box">
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <button class="button is-primary" type="submit">Zmień hasło</button>
      </form>
    </div>
  </div>
</section>
{% endblock %}

templates/edit_profile.html
{% extends 'base.html' %} {% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Edytuj profil</h1>
    <div class="box">
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <button class="button is-primary" type="submit">Zapisz zmiany</button>
      </form>
    </div>
  </div>
</section>
{% endblock %}

templates/hero.html
{% load static %}
<!doctype html>
<html lang="en" style="height: 100%; margin: 0; padding: 0; box-sizing: border-box; overflow: hidden">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Klub 100 Kilo</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <style>
      body {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        overflow: hidden;
      }
      .button.is-primary {
        background-color: #add8e6;
        border-radius: 20px;
      }
      .button.is-link {
        background-color: #ffffff;
        color: #000000;
        border-radius: 20px;
      }
      h1 {
        color: #808080;
        font-size: 2.5rem;
      }
      h2 {
        color: #d3d3d3;
        font-size: 1.5rem;
      }
      .image img {
        border: 5px solid #fff;
        box-shadow: 0 2px 3px rgba(0, 0, 0, 0.1);
      }
    </style>
  </head>
  <body>
    <section class="hero is-fullheight" style="background-color: #ffffff; height: 100vh">
      <div class="hero-body">
        <div class="container">
          <div class="columns is-vcentered">
            <div class="column is-6">
              <h1 class="title">Klub 100 Kilo</h1>
              <h2 class="subtitle">Zaloguj się lub zarejestruj, aby korzystać z naszych usług.</h2>
              <div class="buttons">
                <a class="button is-primary" href="/login">Zaloguj się</a>
                <a class="button is-link" href="/signup">Dołącz do nas</a>
              </div>
            </div>
            <div class="column is-6">
              <figure class="image is-512x512">
                <img src="{% static 'images/hero.png' %}" alt="Man working out" />
              </figure>
            </div>
          </div>
        </div>
      </div>
    </section>
    <footer class="footer" style="padding: 1rem 1.5rem">
      <div class="content has-text-centered">
        <p>
          <strong>Authors</strong>
          <a href="https://github.com/Davsooonowy">Dawid Mularczyk</a>,
          <a href="https://github.com/HadesXBloodFire2024">Maciej Wilewski</a>. 2024
        </p>
      </div>
    </footer>
  </body>
</html>

templates/login.html
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
  </head>
  <body>
    {% if messages %}
    <div class="notification is-danger">
      {% for message in messages %}
      <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}
    <section class="section">
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-half">
            <div class="box">
              <h1 class="title has-text-centered">Zaloguj się</h1>
              <form method="POST">
                {% csrf_token %} {{ form.as_p }}
                <div class="field">
                  <div class="control has-text-centered">
                    <button type="submit" class="button is-link">Zaloguj się</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

templates/main.html
{% extends 'base.html' %} {% block content %}
<link rel="stylesheet" href="../static/styles/main.css" />
<section class="section">
  <div class="container">
    <h2 class="title">Najbliższe treningi</h2>
    <div class="columns is-multiline">
      {% for reservation in reservations %}
      <div class="column is-one-third">
        <div class="card">
          <div class="card-content">
            <p class="title">{{ reservation.name }}</p>
            <p class="subtitle">{{ reservation.start }} - {{ reservation.end|date:"H:i" }}</p>
            <p class="subtitle">
              {% if reservation.trainer %}
              Trener: {{ reservation.trainer.first_name }}
              {{ reservation.trainer.last_name }}
              {% else %}
              Brak trenera
              {% endif %}
            </p>
            <a href="http://127.0.0.1:8000/book_trainer/"><i class="edit-icon fas fa-pencil-alt"></i></a>
            <a href="#" class="delete-icon" data-id="{{ reservation.reservation_id }}"><i class="fas fa-times"></i></a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
<section class="section">
  <div class="container">
    <h2 class="title">Cele treningowe</h2>
    {% for goal in goals %}
    <div class="card">
      <div class="card-content">
        <p class="title">{{ goal.name }}</p>
        <p class="subtitle">Maksymalna liczba dni: {{ goal.max_days }} </p>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

  <section class="section">
  <div class="container">
    <h2 class="title">Ostatnie treningi</h2>
    <div class="columns is-multiline">
      {% for reservation in past_reservations %}
      <div class="column is-one-third">
        <div class="card">
          <div class="card-content">
            <p class="title">{{ reservation.name }}</p>
            <p class="subtitle">{{ reservation.start }} - {{ reservation.end|date:"H:i" }}</p>
            <p class="subtitle">
              {% if reservation.trainer %}
              Trener: {{ reservation.trainer.first_name }} {{ reservation.trainer.last_name }}
              {% else %}
              Brak trenera
              {% endif %}
            </p>
            <p class="subtitle">
              {% if reservation.training_id %}
              Trening: {{ reservation.training.name }}
              Ćwiczenia:
              <ul>
                {% for training_exercise in reservation.training.traningsexercises_set.all %}
                {% if training_exercise.succeded %}
                <li>{{ training_exercise.exercise.description }}</li>
                {% endif %}
                {% endfor %}
              </ul>
              {% else %}
              Brak treningu
              {% endif %}
            </p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <h2 class="title">Twoje treningi</h2>
    {% for training in trainings %}
    <div class="card">
      <div class="card-content">
        <p class="title">{{ training.name }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
<script>
document.querySelectorAll('.delete-icon').forEach(function(deleteIcon) {
  deleteIcon.addEventListener('click', function(event) {
    event.preventDefault();
    var reservationId = this.getAttribute('data-id');
    if (confirm("Are you sure you want to remove it?")) {
      $.ajax({
        type: "GET",
        url: '/remove',
        data: {'id': reservationId},
        dataType: "json",
        success: function(response) {
          console.log('Success response:', response);
          location.reload();
          alert('Event Removed');
        },
        error: function(response) {
          console.log('Error response:', response);
          alert('There was an error. Please try again.');
        }
      });
    }
  });
});
</script>
</section>
</section>
{% endblock %}

templates/register.html
<!-- register.html -->
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
  </head>
  <body>
    {% if messages %}
    <div class="notification is-danger">
      {% for message in messages %}
      <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}
    <section class="section">
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-half">
            <div class="box">
              <h1 class="title has-text-centered">Zarejestruj się</h1>
              <form method="POST">
                {% csrf_token %} {{ form.as_p }}
                <div class="field">
                  <div class="control has-text-centered">
                    <button type="submit" class="button is-link">Zarejestruj się</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

templates/workouts.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="../static/styles/workouts.css" />
<div id="trainings-list">
    {% for reservation in reservations %}
        {% if reservation.training_id %}
            <div class="card">
                <div class="card-content">
                    <p class="title">{{ reservation.name }}</p>
                    <p class="subtitle">{{ reservation.start }} - {{ reservation.end|date:"H:i" }}</p>
                    <div>
                        <div class="training-name" onclick="document.getElementById('view-training-popup-{{ reservation.training_id }}').style.display='block'">
                            {{ reservation.training.name }}
                        </div>

                    </div>

                    <div id="view-training-popup-{{ reservation.training_id }}" class="popup">
                        <form method="POST" action="{% url 'mark_exercises_as_succeeded' reservation.training_id %}">
                            {% csrf_token %}
                            {% for training_exercise in reservation.training.traningsexercises_set.all %}
                                <input type="checkbox" id="exercise-{{ reservation.training.training_id }}-{{ training_exercise.exercise.exercise_id }}" name="exercises" value="{{ training_exercise.exercise.exercise_id }}" {% if training_exercise.succeded %}checked{% endif %}>
                                <label for="exercise-{{ reservation.training.training_id }}-{{ training_exercise.exercise.exercise_id }}">{{ training_exercise.exercise.description }}</label><br>
                            {% endfor %}
                            <input type="submit" value="Zapisz">
                        </form>
                        <form method="POST" action="{% url 'delete_training' reservation.training_id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Usuń trening</button>
                        </form>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="card">
                <div class="card-content">
                    <p class="title">{{ reservation.name }}</p>
                    <p class="subtitle">{{ reservation.start }} - {{ reservation.end|date:"H:i" }}</p>
                    <form action="{% url 'create_training' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="reservation_id" value="{{ reservation.reservation_id }}">
                    <input type="text" id="training-name" name="name" placeholder="Nazwa treningu" required>
                    {% for exercise in exercises %}
                    <div>
                        <input type="checkbox" id="exercise{{ exercise.exercise_id }}" name="exercises" value="{{ exercise.exercise_id }}">
                        <label for="exercise{{ exercise.exercise_id }}">{{ exercise.description }}</label>
                    </div>
                    {% endfor %}
                    <input type="submit" id="toggleCreateTrainingForm" value="Utwórz trening">
                </form>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
<script>
    window.onload = function() {
        var nameInput = document.getElementById('training-name');
        var checkboxes = document.getElementsByName('exercises');
        var submitButton = document.getElementById('toggleCreateTrainingForm');

        function checkInputs() {
            var nameGiven = nameInput.value !== '';
            var exerciseChosen = Array.prototype.slice.call(checkboxes).some(x => x.checked);
            submitButton.disabled = !(nameGiven && exerciseChosen);
        }

        nameInput.addEventListener('input', checkInputs);
        checkboxes.forEach(function(checkbox) {
            checkbox.addEventListener('change', checkInputs);
        });

        checkInputs();
    };
</script>
{% endblock %}